# Redirect /heart-bits/ to /contao
heartbits_backend_redirect:
    path: /heart-bits/
    defaults:
        _scope: backend
        _controller: "FrameworkBundle:Redirect:redirect"
        route: contao_backend
        permanent: true
